Homework 1
infinum-academy/js-react-academy-2024-fran-galic pull request #1
Opened 2024-07-04 13:17 UTC by fran-galic

Prva domaća zadaća za React. Napravljena sva 3 zadatka :)

2024-07-05 13:29 UTC, veksi requested changes
Dobro si ovo napravio :)

Pogledaj komentare, i probaj ispraviti što više.
Ukoliko ne stigneš prodđemo zajedno na sljedećim konzultacijama.

2024-07-05 13:29 UTC, veksi commented on project/index.html
> +               <input type="button" value="Post" onclick="addReview()" class="post-button">
Zasto ne `button` element? Što dobijemo sa` input type="button"` ?

2024-07-05 13:29 UTC, veksi commented on project/index.html
> +            <form class="reviews-form">
Super što koristiš form element ovdje. Dobra ideja bi bila napraviti kreiranja review-a kroz form submit flow u tom slučaju.
Možemo ovo proći kroz neke od sljedećih konzultacija.

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +var reviews = [];
Dobra praksa je koristiti `const` i `let` kao identifikatore varijabli. 
var je relativno "unsafe" i praktički nikad ga nećemo koristiti.

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +   reviews.push(reviewObject);
Bilo bi dobro prije nego što dodaš novi review provjeriti je li "validan".
Staviti neki guard ukoliko korisnik nije unio description i rating da ignoriras submit.

2024-07-05 13:29 UTC, veksi commented on project/index.html
> +               <textarea name="tijelo" rows="10" cols="50" class="main-description" required>Add review</textarea>
S obzirom da ne radis trigger submit flow-a kroz form event (submit) required property ne znači puno :) tj. neće onemogućit korisnika za daljnju akciju.

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +   document.querySelector(".main-description").value = "Add review";
Dobra praksa je ne raditi prefill value-a kod inputa (pogotovo formi) već `placeholder` attributa.

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +function rednerReviews() {
Mali typo :)

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +if (tempReviews !== null) reviews = tempReviews;
Malo ljepši (jednostavniji) način za postići isto:

```suggestion
reviews = loadFromLocalStorage() || [];
```

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +   localStorage.clear();
Postoji neki razlog zašto radiš clear cijelog localStorage-a prije save-a?

Ovo nije dobra ideja jer možeš pobrisati i neke podatke koji ti možda trebaju.
U budućnosti će možda neki servis spremiti neki identifikator ili sl. u localStorage, a ti češ ga pobrisati i app će možda prestati raditi.
Ukoliko si htio pobrisati svoje reviewove to si mogao sa:
`localStorage.removeItem('reviews')`
Međutim, `setItem` funkcija u ovom slučaju će napraviti rewrite kod svakog spremanja, tako da ti clear ili remove nisu potrebni :)

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +   var deleteButton = document.createElement("input");
Puno bolja, tj. točnija opcija bi bila kreirati direktno button element

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +   if(![1, 2, 3, 4, 5].includes(parseInt(review.grade))) return;
Mogao si ovo smo ovo jednostavnije napraviti :) ali ovdje nam čak i nije trebao nekakav guard.
Štoviše, s ovim guardom nisi napravio ništa jer se review i dalje napravi i spremi u localStorage, samo ga ne renderas a razlog je redoslijed provjera i akcija koje imas u addReview funkciji :)
Mozemo ovo proci na konzultacijama

2024-07-05 13:29 UTC, veksi commented on project/index.js
> +      star.setAttribute('data-value', i);
Super ideja za data attribute!

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   padding: 0 10% 30px 10%;
Izbjegavaj propertye kao padding, margin i sl. definirati u % (radi responzivnosti). Teško ih je debuggirati i dobiti točnu vrijednost koja nam stv. treba :)

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   flex: row nowrap;
pretpostavljam da si htio flex-flow ovdje ali nam ovdje flex kao takav nije potreban :) imas 1 element samo

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   flex: 0 1 auto;
Što si htio postići s ovim stilom?

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   flex: 1 1 none; /* Fleksibilnost rasta i skupljanja slike */
poprilično sam siguran da ovo nije validno, tj. da se stil ne apply-a

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   border-radius: 30px 30px 0 0;
Vjerovatno si primjetio da kontejner gdje je slika i description ima border radius (u tvom slučaju .show-information).
Puno jednostavnija opcija bi bila njemu staviti `border-radius: 30px` da se radius apply-a na svim stranama, i njemu staviti `overflow: hidden`, što će odrezati sve elemente unutar njega ukoliko prelaze van granica. To bi automatski odrezala rubove slike, tj. napravila ih zaobljenim :)

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   border-radius: 0 0 30px 30px;
Pogledaj komentar gore :)

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   transform: translateY(-2px); /* Pomeranje nagore za 5px */
Fora efekt, ali čemo ga rijetko koristiti u stvarnosti (korisnici ne vole da im stvari skaču po ekranu, pgotovo kad hoveraju na nesto).
Nešto što ćemo češće raditi na hover su npr: `transform: scale(1.1)` ili promjena pozadine i sl.

2024-07-05 13:29 UTC, veksi commented on project/styles.css
> +   padding: 1.8rem 1rem;
Slično kao i %, dosta teško ispratiti koja je stvarna vrijednost padding-a :)

2024-07-05 13:47 UTC, fran-galic commented
Moze ispravim cim prije, pozdrav

pet, 5. srp 2024. 15:30 Vedran Serenčeš ***@***.***> je
napisao:

> ***@***.**** requested changes on this pull request.
>
> Dobro si ovo napravio :)
>
> Pogledaj komentare, i probaj ispraviti što više.
> Ukoliko ne stigneš prodđemo zajedno na sljedećim konzultacijama.
> ------------------------------
>
> In project/index.html
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666776433>
> :
>
> > +            </div>
> +         </div>
> +
> +         <div class="reviews-form-container">
> +            <div>Reviews</div>
> +            <form class="reviews-form">
> +               <textarea name="tijelo" rows="10" cols="50" class="main-description" required>Add review</textarea>
> +               <div class="rating-input">
> +                  <span>Rating </span>
> +                  <span class="star" data-value="1">&#9733;</span>
> +                  <span class="star" data-value="2">&#9733;</span>
> +                  <span class="star" data-value="3">&#9733;</span>
> +                  <span class="star" data-value="4">&#9733;</span>
> +                  <span class="star" data-value="5">&#9733;</span>
> +              </div>
> +               <input type="button" value="Post" onclick="addReview()" class="post-button">
>
> Zasto ne button element? Što dobijemo sa input type="button" ?
> ------------------------------
>
> In project/index.html
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666777695>
> :
>
> > +
> +      <!-- Sredisnji dio stranice -->
> +      <div class="main">
> +         <div class="show-information">
> +            <img src="./images/breaking_bad.jpg" alt="visual of the series" class="show-image">
> +            <div class="show-description-container">
> +               <div class="series-title">Breaking Bad</div>
> +               <div class="series-description">Breaking Bad follows Walter White, a struggling, frustrated high
> +                  school chemistry teacher who becomes a crimelord in the local methamphetamine drug trade, driven to
> +                  provide for his family financially after being diagnosed with inoperable lung cancer.</div>
> +            </div>
> +         </div>
> +
> +         <div class="reviews-form-container">
> +            <div>Reviews</div>
> +            <form class="reviews-form">
>
> Super što koristiš form element ovdje. Dobra ideja bi bila napraviti
> kreiranja review-a kroz form submit flow u tom slučaju.
> Možemo ovo proći kroz neke od sljedećih konzultacija.
> ------------------------------
>
> In project/index.js
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666778804>
> :
>
> > @@ -0,0 +1,145 @@
> +var reviews = [];
>
> Dobra praksa je koristiti const i let kao identifikatore varijabli.
> var je relativno "unsafe" i praktički nikad ga nećemo koristiti.
> ------------------------------
>
> In project/index.js
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666784035>
> :
>
> > +function callAvgRating() {
> +   var sum = 0;
> +   if (reviews.length == 0) return 0;
> +
> +   reviews.forEach((r) => {
> +      sum += r.grade;
> +   });
> +   return (sum / reviews.length).toFixed(1);
> +}
> +
> +function addReview() {
> +   reviewObject = {};
> +   reviewObject.description = document.querySelector(".main-description").value;
> +   reviewObject.grade = currentRatingValue;
> +
> +   reviews.push(reviewObject);
>
> Bilo bi dobro prije nego što dodaš novi review provjeriti je li "validan".
> Staviti neki guard ukoliko korisnik nije unio description i rating da
> ignoriras submit.
> ------------------------------
>
> In project/index.html
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666784783>
> :
>
> > +      <!-- Sredisnji dio stranice -->
> +      <div class="main">
> +         <div class="show-information">
> +            <img src="./images/breaking_bad.jpg" alt="visual of the series" class="show-image">
> +            <div class="show-description-container">
> +               <div class="series-title">Breaking Bad</div>
> +               <div class="series-description">Breaking Bad follows Walter White, a struggling, frustrated high
> +                  school chemistry teacher who becomes a crimelord in the local methamphetamine drug trade, driven to
> +                  provide for his family financially after being diagnosed with inoperable lung cancer.</div>
> +            </div>
> +         </div>
> +
> +         <div class="reviews-form-container">
> +            <div>Reviews</div>
> +            <form class="reviews-form">
> +               <textarea name="tijelo" rows="10" cols="50" class="main-description" required>Add review</textarea>
>
> S obzirom da ne radis trigger submit flow-a kroz form event (submit)
> required property ne znači puno :) tj. neće onemogućit korisnika za daljnju
> akciju.
> ------------------------------
>
> In project/index.js
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666785533>
> :
>
> > +
> +   reviews.forEach((r) => {
> +      sum += r.grade;
> +   });
> +   return (sum / reviews.length).toFixed(1);
> +}
> +
> +function addReview() {
> +   reviewObject = {};
> +   reviewObject.description = document.querySelector(".main-description").value;
> +   reviewObject.grade = currentRatingValue;
> +
> +   reviews.push(reviewObject);
> +   rednerReviews();
> +
> +   document.querySelector(".main-description").value = "Add review";
>
> Dobra praksa je ne raditi prefill value-a kod inputa (pogotovo formi) već
> placeholder attributa.
> ------------------------------
>
> In project/index.js
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666785799>
> :
>
> > +function addReview() {
> +   reviewObject = {};
> +   reviewObject.description = document.querySelector(".main-description").value;
> +   reviewObject.grade = currentRatingValue;
> +
> +   reviews.push(reviewObject);
> +   rednerReviews();
> +
> +   document.querySelector(".main-description").value = "Add review";
> +   currentRatingValue = 0;
> +   resetStars();
> +
> +   saveToLocalStorage(reviews);
> +}
> +
> +function rednerReviews() {
>
> Mali typo :)
> ------------------------------
>
> In project/index.js
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666788014>
> :
>
> > +var tempReviews = loadFromLocalStorage();
> +if (tempReviews !== null) reviews = tempReviews;
>
> Malo ljepši (jednostavniji) način za postići isto:
> ⬇️ Suggested change
>
> -var tempReviews = loadFromLocalStorage();
> -if (tempReviews !== null) reviews = tempReviews;
> +reviews = loadFromLocalStorage() || [];
>
> ------------------------------
>
> In project/index.js
> <https://github.com/infinum-academy/js-react-academy-2024-fran-galic/pull/1#discussion_r1666792514>
> :
>
> > +   if (oldScore !== null) oldScore.remove();
> +
> +   var avgScoreDiv = createAvgScoreDiv(avgRating);
> +   document.querySelector(".show-description-container").appendChild(avgScoreDiv);
> +}
> +
> +function createAvgScoreDiv(avgRating) {
> +   var avgScoreDiv = document.createElement("div");
> +   avgScoreDiv.classList.add('avg-score');
> +   avgScoreDiv.innerHTML = (avgRating + "/5");
> +   return avgScoreDiv;
> +}
> +
> +//funkcije za localStorage:
> +function saveToLocalStorage(reviews) {
> +   localStorage.clear();
>
> Postoji neki razlog zašto radiš clear cijelog localStorage-a prije save-a?
>
> Ovo nije dobra ideja jer možeš pobrisati i neke podatke koji ti možda
> trebaju.
> U budućnosti će možda neki servis spremiti neki identifikator ili sl. u
> localStorage, a ti češ ga pobrisati i app će možda prestati raditi.
> Ukoliko si htio pobrisati svoje reviewove to si mogao sa:
> localStorage.removeItem('reviews')
> Međutim, setItem funkcija u ovom slučaju će napr [...]

2024-07-12 11:46 UTC, veksi approved these changes

2024-07-12 11:46 UTC, merged