Homework 2
infinum-academy/js-react-academy-2024-fran-galic pull request #2
Opened 2024-07-10 17:43 UTC by fran-galic

Napravljena 2. Dz sa malo kašnjenja. Sve je napravljeno probat ću još napravit i bonus dio.
Nekoliko pitanja sam stavio u README.md za koje bi volio da ih prođemo na konzultacijama ako je moguće.
Lijep pozdrav :)

2024-07-10 21:35 UTC, veksi requested changes
Meni ovo izgleda dobro!
Imaš par sitnih komentara kroz koje prođemo na konzultacijama i ako nam ostane vremena probamo zajedno napraviti bonus!

Ne vidim u README nikakva pitanje, ali možemo proći što god si htio pitati :))

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/app/layout.tsx
> +          <Box bg="#200050" color='white' paddingLeft={4} paddingRight={4} paddingBottom={4}>
Ovo je okej ali mogli smo ovo i kraće napisati:
```suggestion
          <Box bg="#200050" color='white' px={4} paddingBottom={4}> 
```

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/app/page.tsx
> +        <ShowDetails show={mockShowIdea} avgRatting={avgRating}/>
Ima li potrebe za 2 prop-a ovdje?
Ja bih radje stavio ovaj mockShowIdea u state (s obzirom da on ima/treba imati averageRating) i onda njemu azurirao average rating. Tako bi onda samo prosljeđivao show objekt :)

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/components/features/review/ReviewItem/ReviewItem.tsx
> +                        </Flex>
Nisi ovo morao ovako, mogao si za sad samo hardkodirati neki avatar url.
Budemo prošli na konzultacijama :)

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/components/features/review/ReviewList/ReviewList.tsx
> +      <Flex gap={5} direction="column">
Negdje koristis `Flex`, negdje `Stack`, slučajno ili?

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +         <Input placeholder='Add rating' borderRadius='xl' bg='white' fontSize='xs' color="black" width={150} size='md' id="grade"/>
Volimo width i height definirani u px (ovo ce realno zapravo biti "150px", pa zasto ne to eksplicitno i napisati)

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +      <Stack spacing='4' maxW='container.sm'>
Ocekivao bih da je ovo neki form element, s obzirom da smo nazvali komponentu ReviewForm.
Prođemo na konzultacijama kako bi ovo inače napravili :)

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/components/features/shows/ShowDetails/ShowDetails.tsx
> +         src={imageUrl === undefined ? "https://fakeimg.pl/600x400?text=No+Image+:(" : imageUrl}
Nije potrebno `imageUrl === undefined `, mozemo direktno napisati
A malo je ovo teško i pročitati, realno mislim da je bolje:

`src={imageUrl ?? "https://fakeimg.pl/600x400?text=No+Image"`
ili
`src={imageUrl ? imageUrl : "https://fakeimg.pl/600x400?text=No+Image"`

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/components/features/shows/ShowDetails/ShowDetails.tsx
> +         borderTopRightRadius='2xl'
Ne treba nam borderRadius ovdje. 
Prođemo na konzultacijama kako smo mogli ovo rjesiti :)

2024-07-10 21:35 UTC, veksi commented on tv-shows-ratting-app/src/components/features/shows/ShowDetails/ShowDetails.tsx
> +                  {avgRatting === undefined ? "no ratings" : avgRatting.toFixed(1) + "/5"}
Ne volimo bas inverzne kondicional rendere tj. provjere, rađe ćemo napravit:
```suggestion
                  {avgRatting ? `${avgRatting.toFixed(1)}/5` : "no ratings"
```

2024-07-11 07:16 UTC, fran-galic commented on tv-shows-ratting-app/src/components/features/review/ReviewList/ReviewList.tsx
> +      <Flex gap={5} direction="column">
Nisam razmišljao o tome da zapravo imaju jako sličnu funkcionalnsot

2024-07-11 08:38 UTC, fran-galic commented on tv-shows-ratting-app/src/components/features/shows/ShowDetails/ShowDetails.tsx
> +         borderTopRightRadius='2xl'
Dodao sam overflow="hidden" na Card komponentu i maknuo sam   borderTopLeftRadius='2xl'
         borderTopRightRadius='2xl' iz Image komponente

2024-07-11 08:57 UTC, fran-galic commented on tv-shows-ratting-app/src/app/page.tsx
> +        <ShowDetails show={mockShowIdea} avgRatting={avgRating}/>
Ispravio

2024-07-12 13:32 UTC, fran-galic commented on tv-shows-ratting-app/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +      <Stack spacing='4' maxW='container.sm'>
Napravljeno :)

2024-07-14 16:36 UTC, veksi approved these changes
Looks good to me 👍

2024-07-14 16:36 UTC, merged